name             'cloudwatch_logs'
maintainer       'Kevin'
maintainer_email 'penniesfromkevin@'
license          'MIT'
description      'Installs and configures CloudWatch Logging.'
version          '0.0.4'
